http:
  port: 8058
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  usersAPI:
    host: 'vue.gateway.sg'
    paths: 
      - '/users/list'
  productsAPI:
    host: 'vue.gateway.sg'
    paths: 
      - '/products/list'
  transactionsAPI:
    host: 'vue.gateway.sg'
    paths: 
      - '/transactions/list'
serviceEndpoints:
  userService:
    url: 'http://localhost:8059'
  productService:
    url: 'http://localhost:8060'
  transactionService:
    url: 'http://localhost:8061'
policies:
#   - expression
#   - key-auth
  - proxy
pipelines:
  - name: user_pipeline
    apiEndpoints:
      - usersAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: userService
            changeOrigin: true
  - name: product_pipeline
    apiEndpoints:
      - productsAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: productService
            changeOrigin: true
  - name: transactions_pipeline
    apiEndpoints:
      - transactionsAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: transactionService
            changeOrigin: true